import type { Instruction, Machine } from "@washy-washy/core/browser";

/**
 * A small, representative machine and chart — not anyone's real laundry, but
 * varied enough to show what this package actually draws: a mix of ironed
 * and never-ironed piles, a couple that share a load, one that can't share
 * with anything.
 */
export const MACHINE: Machine = {
  washer: {
    name: "Generic front loader",
    capacity: "1–8 kg",
    programs: ["Off", "Cottons", "Easy Care", "Delicates / Silk", "Wool"],
    temperatures: ["cold", "20", "30", "40", "60"],
    spins: ["0", "400", "800", "1200", "1400"],
    options: ["Eco", "Extra Rinse"],
  },
  iron: {
    name: "Generic steam iron",
    settings: [
      { key: "min", dots: "", label: "MIN", detail: "no heat", steam: false },
      { key: "1", dots: "•", label: "•", detail: "synthetics", steam: false },
      { key: "2", dots: "••", label: "••", detail: "wool, silk", steam: true },
      { key: "3", dots: "•••", label: "•••", detail: "cotton, linen", steam: true },
    ],
  },
};

export const CHART: Instruction[] = [
  {
    clothingType: "Whites",
    detergent: "Universal powder, full dose",
    fabricSoftener: false,
    temperature: "60",
    spin: "1200",
    duration: "~2:30",
    program: "Cottons",
    options: ["Eco"],
    ironing: true,
    ironingNotes: "Iron while slightly damp, steam on.",
    ironSetting: "3",
    drying: "Tumble dry normal, or line dry in the sun.",
    colourGroup: "white",
    mixTags: [],
    notes: "Wash whites on their own.",
  },
  {
    clothingType: "Coloured shirts",
    detergent: "Colour liquid detergent",
    fabricSoftener: true,
    temperature: "40",
    spin: "1200",
    duration: "~2:15",
    program: "Cottons",
    options: ["Eco"],
    ironing: true,
    ironingNotes: "Steam, turn prints inside out first.",
    ironSetting: "3",
    drying: "Line dry inside out, or tumble on low.",
    colourGroup: "colour",
    mixTags: [],
    notes: "",
  },
  {
    clothingType: "Dark jeans",
    detergent: "Liquid detergent for dark/black",
    fabricSoftener: false,
    temperature: "30",
    spin: "800",
    duration: "~2:00",
    program: "Cottons",
    options: ["Extra Rinse"],
    ironing: false,
    ironingNotes: "",
    ironSetting: "",
    drying: "Hang by the waistband and air dry.",
    colourGroup: "dark",
    mixTags: ["dye-bleeder"],
    notes: "Inside out, zips and buttons closed.",
  },
  {
    clothingType: "Merino jumper",
    detergent: "Wool detergent, half dose",
    fabricSoftener: false,
    temperature: "30",
    spin: "400",
    duration: "~0:40",
    program: "Wool",
    options: [],
    ironing: true,
    ironingNotes: "Only if you must: pressing cloth, no weight.",
    ironSetting: "2",
    drying: "Dry flat on a towel, away from radiators.",
    colourGroup: "any",
    mixTags: [],
    notes: "Turn inside out, wash with wool only.",
  },
  {
    clothingType: "Synthetic activewear",
    detergent: "A small dose of mild pH-neutral liquid detergent",
    fabricSoftener: false,
    temperature: "30",
    spin: "800",
    duration: "~1:10",
    program: "Easy Care",
    options: ["Extra Rinse"],
    ironing: false,
    ironingNotes: "",
    ironSetting: "",
    drying: "Air dry on a hanger, within the hour.",
    colourGroup: "sport",
    mixTags: ["lint-magnet"],
    notes: "Inside out. Never softener.",
  },
];
